---
- name: install jumpbox packages
  apt: name={{ packages }} update_cache=yes state=present
  vars:
    packages:
      # These are mostly dependencies for datagov-deploy's requirements.txt
      - dsh
      - git
      - libffi-dev
      - libssl-dev
      - openssh-server
      - python-dev
      - python-pip
      - python-virtualenv

- name: Create operators group
  group: name=operators state=present

- name: Add ubuntu user to operators group
  user:
    name: ubuntu
    groups:
      - operators

- name: Create data.gov configuration directory
  file: path=/etc/datagov state=directory owner=root group=operators mode=0750

- name: Configure ansible
  copy: src=ansible.cfg dest=/etc/datagov/ansible.cfg owner=root group=operators mode=0644

- name: Create operator accounts
  user:
    name: "{{ item.username }}"
    comment: "{{ item.email }}"
    groups:
      - operators
    shell: /bin/bash
    state: "present"
    password_lock: yes
    expires: -1
  with_items: "{{ jumpbox_operators }}"
  register: user_account

- name: Determine existing operators
  shell: |
    set -o pipefail
    grep operators /etc/group | cut -d: -f4 | tr "," "\n" | grep -v "^ubuntu$"
  args:
    executable: /bin/bash
  changed_when: false
  register: existing_users

- name: Simplify jumpbox_operators as an array for comparison with current users
  set_fact:
    # Sets a list of mount directories
    jumpbox_operators_list: "\
      {{ jumpbox_operators_list | default([]) }} + \
      [ '{{ item['username'] }}' ]"
  with_items: "{{ jumpbox_operators }}"

- name: Determine users to remove
  set_fact:
    removed_users: "{{ existing_users.stdout_lines | difference(jumpbox_operators_list) }}"

- name: Delete user accounts no longer registered
  user:
    name: "{{ item }}"
    state: absent
  with_items: "{{ removed_users }}"

- name: Disable password max age
  command: chage -I -1 -M -1 {{ item.item.username }}
  with_items: "{{ user_account.results }}"
  when:
    - item.item.active | default(false)
    - item is changed

- name: Add SSH public key directory structure
  file: >-
    path=/home/{{ item.username }}/.ssh
    state=directory
    mode=0700
    owner={{ item.username }}
    group={{ item.username }}
  with_items: "{{ jumpbox_operators }}"

- name: Add SSH public key directory structure for ubuntu
  file: >-
    path=/home/ubuntu/.ssh
    state=directory
    mode=0700
    owner=ubuntu
    group=ubuntu

- name: Copy SSH public key
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.public_key }}"
    exclusive: True
    state: "present"
  with_items: "{{ jumpbox_operators }}"

- name: Update ssh config with inventory for auto completion
  template:
    src: ssh_config.j2
    dest: /home/{{ item.username }}/.ssh/config
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: 0640
  with_items: "{{ jumpbox_operators }}"

- name: Update ssh config with inventory for auto completion for ubuntu user
  template:
    dest: /home/ubuntu/.ssh/config
    src: ssh_config.j2
    owner: ubuntu
    group: ubuntu
    mode: 0640
    force: no

- name: Allow 'operators' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%operators'
    line: '%operators ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: Remove all operators users from sudoers
  file: >-
    dest=/etc/sudoers.d/{{ item }}
    state=absent
  with_items: "{{ existing_users.stdout_lines + jumpbox_operators_list }}"

- name: Configure dsh
  template: src=etc_dsh_dsh.conf.j2 dest=/etc/dsh/dsh.conf mode=0644 owner=root group=root

- name: Configure dsh groups
  copy:
    content: "{{ groups[item] | sort() | join('\n') }}"
    dest: /etc/dsh/group/{{ item }}
    mode: "0644"
    owner: root
    group: root
  loop: "{{ groups | list }}"

- name: Increase TMUX scrollback buffer size
  copy:
    content: "set-option -g history-limit 20000"
    dest: /home/ubuntu/.tmux.conf

- name: Create folder for ansible playbook logs
  file:
    path: /home/ubuntu/datagov-deploy/ansible/logs
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0775

- name: Add ANSIBLE_LOG_PATH to env
  lineinfile:
    path: /home/ubuntu/datagov-deploy/.env
    state: present
    create: yes
    line: 'ANSIBLE_LOG_PATH=/home/ubuntu/datagov-deploy/ansible/logs/ansible.log'
