---
- name: install jumpbox packages
  apt: name={{ item }} update_cache=yes state=present
  with_items:
    # These are mostly dependencies for datagov-deploy's requirements.txt
    - git
    - libffi-dev
    - libssl-dev
    - openssh-server
    - python-dev
    - python-pip
    - python-virtualenv

- name: Create/remove the user account
  user:
    name: "{{ item.username }}"
    comment: "{{ item.email }}"
    shell: /bin/bash
    state: "{{ item.removed is defined and 'absent' or 'present' }}"
    password_lock: yes
    expires: -1
  with_items: "{{ jumpbox_operators }}"

- name: Add SSH public key directory structure
  file: >-
    path=/home/{{ item.username }}/.ssh
    state=directory
    mode=0700
    owner={{ item.username }}
    group={{ item.username }}
  when: item.removed is undefined
  with_items: "{{ jumpbox_operators }}"

- name: Add SSH public key directory structure for ubuntu
  file: >-
    path=/home/ubuntu/.ssh
    state=directory
    mode=0700
    owner=ubuntu
    group=ubuntu

- name: Copy SSH public key
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.public_key }}"
    exclusive: True
    state: "present"
  when: item.removed is not defined
  with_items: "{{ jumpbox_operators }}"

- name: Update ssh config with inventory for auto completion
  template:
    src: ssh_config.j2
    dest: /home/{{ item.username }}/.ssh/config
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: 0640
    force: no
  when: item.removed is not defined
  with_items: "{{ jumpbox_operators }}"

- name: Update ssh config with inventory for auto completion for ubuntu user
  template:
    dest: /home/ubuntu/.ssh/config
    src: ssh_config.j2
    owner: ubuntu
    group: ubuntu
    mode: 0640
    force: no

- name: Update the system /etc/sudoers file
  template: >-
    src=sudoers.j2
    dest=/etc/sudoers.d/{{ item.username }}
    mode=0600
  when: item.removed is not defined
  with_items: "{{ jumpbox_operators }}"

- name: Remove sudoers for removed users
  file: >-
    dest=/etc/sudoers.d/{{ item.username }}
    state=absent
  when: item.removed is defined
  with_items: "{{ jumpbox_operators }}"
